# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datatypes/ros/std_msgs/Header.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from datatypes.ros import builtins_pb2 as datatypes_dot_ros_dot_builtins__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='datatypes/ros/std_msgs/Header.proto',
  package='ros.std_msgs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n#datatypes/ros/std_msgs/Header.proto\x12\x0cros.std_msgs\x1a\x1c\x64\x61tatypes/ros/builtins.proto\"A\n\x06Header\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\x18\n\x05stamp\x18\x02 \x01(\x0b\x32\t.ros.Time\x12\x10\n\x08\x66rame_id\x18\x03 \x01(\tb\x06proto3'
  ,
  dependencies=[datatypes_dot_ros_dot_builtins__pb2.DESCRIPTOR,])




_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='ros.std_msgs.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq', full_name='ros.std_msgs.Header.seq', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stamp', full_name='ros.std_msgs.Header.stamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='ros.std_msgs.Header.frame_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=148,
)

_HEADER.fields_by_name['stamp'].message_type = datatypes_dot_ros_dot_builtins__pb2._TIME
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {
  'DESCRIPTOR' : _HEADER,
  '__module__' : 'datatypes.ros.std_msgs.Header_pb2'
  # @@protoc_insertion_point(class_scope:ros.std_msgs.Header)
  })
_sym_db.RegisterMessage(Header)


# @@protoc_insertion_point(module_scope)
