# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datatypes/ros/sensor_msgs/CompressedImage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from datatypes.ros.std_msgs import Header_pb2 as datatypes_dot_ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='datatypes/ros/sensor_msgs/CompressedImage.proto',
  package='ros.sensor_msgs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n/datatypes/ros/sensor_msgs/CompressedImage.proto\x12\x0fros.sensor_msgs\x1a#datatypes/ros/std_msgs/Header.proto\"U\n\x0f\x43ompressedImage\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x62\x06proto3'
  ,
  dependencies=[datatypes_dot_ros_dot_std__msgs_dot_Header__pb2.DESCRIPTOR,])




_COMPRESSEDIMAGE = _descriptor.Descriptor(
  name='CompressedImage',
  full_name='ros.sensor_msgs.CompressedImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ros.sensor_msgs.CompressedImage.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='format', full_name='ros.sensor_msgs.CompressedImage.format', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='ros.sensor_msgs.CompressedImage.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=190,
)

_COMPRESSEDIMAGE.fields_by_name['header'].message_type = datatypes_dot_ros_dot_std__msgs_dot_Header__pb2._HEADER
DESCRIPTOR.message_types_by_name['CompressedImage'] = _COMPRESSEDIMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CompressedImage = _reflection.GeneratedProtocolMessageType('CompressedImage', (_message.Message,), {
  'DESCRIPTOR' : _COMPRESSEDIMAGE,
  '__module__' : 'datatypes.ros.sensor_msgs.CompressedImage_pb2'
  # @@protoc_insertion_point(class_scope:ros.sensor_msgs.CompressedImage)
  })
_sym_db.RegisterMessage(CompressedImage)


# @@protoc_insertion_point(module_scope)
