# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datatypes/ros/sensor_msgs/PointField.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='datatypes/ros/sensor_msgs/PointField.proto',
  package='ros.sensor_msgs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n*datatypes/ros/sensor_msgs/PointField.proto\x12\x0fros.sensor_msgs\"K\n\nPointField\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\r\x12\x10\n\x08\x64\x61tatype\x18\x03 \x01(\x05\x12\r\n\x05\x63ount\x18\x04 \x01(\rb\x06proto3'
)




_POINTFIELD = _descriptor.Descriptor(
  name='PointField',
  full_name='ros.sensor_msgs.PointField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ros.sensor_msgs.PointField.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='ros.sensor_msgs.PointField.offset', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='datatype', full_name='ros.sensor_msgs.PointField.datatype', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='ros.sensor_msgs.PointField.count', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=138,
)

DESCRIPTOR.message_types_by_name['PointField'] = _POINTFIELD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PointField = _reflection.GeneratedProtocolMessageType('PointField', (_message.Message,), {
  'DESCRIPTOR' : _POINTFIELD,
  '__module__' : 'datatypes.ros.sensor_msgs.PointField_pb2'
  # @@protoc_insertion_point(class_scope:ros.sensor_msgs.PointField)
  })
_sym_db.RegisterMessage(PointField)


# @@protoc_insertion_point(module_scope)
